commit_types:
  - label: 'refactor'
    detail: 'Select when no new performances or no new functionality'
    prefix: 'refactor âš™ï¸'
  - label: 'performance'
    detail: 'Select when working on performances'
    prefix: 'perf âš¡'
  - label: 'feature'
    detail: 'Select when adding new functionality'
    prefix: 'feat ğŸ¦„'
  - label: 'fix'
    detail: 'Select when fixing a bug'
    prefix: 'fix ğŸ'
  - label: 'docs'
    detail: 'Select when writing documentation'
    prefix: 'docs ğŸ“„'
  - label: 'test'
    detail: 'Select when adding tests'
    prefix: 'test ğŸª–'
  - label: 'ci'
    detail: 'Select when working on CI'
    prefix: 'ci ğŸš€'
  - label: 'build'
    detail: 'Select when concerning build change or external dependencies'
    prefix: 'build ğŸ–¥ï¸'
  - label: 'style'
    detail: 'Select when working on style'
    prefix: 'style ğŸŒˆ'
  - label: 'revert'
    detail: 'Select when reverting a commit'
    prefix: 'revert âª'